// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFiles(arg1) {
  return window['go']['main']['App']['AddRecentFiles'](arg1);
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function DeleteParseResult(arg1) {
  return window['go']['main']['App']['DeleteParseResult'](arg1);
}

export function ExportData(arg1, arg2) {
  return window['go']['main']['App']['ExportData'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetParseResult(arg1) {
  return window['go']['main']['App']['GetParseResult'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function OpenFiles() {
  return window['go']['main']['App']['OpenFiles']();
}

export function ParseFile(arg1) {
  return window['go']['main']['App']['ParseFile'](arg1);
}

export function RemoveRecentFile(arg1) {
  return window['go']['main']['App']['RemoveRecentFile'](arg1);
}

export function SaveParseResult(arg1, arg2) {
  return window['go']['main']['App']['SaveParseResult'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectExportDir() {
  return window['go']['main']['App']['SelectExportDir']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
