// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function AddRecentFiles(arg1:Array<main.RecentFile>):Promise<Array<main.RecentFile>>;

export function ClearRecentFiles():Promise<Array<main.RecentFile>>;

export function DeleteParseResult(arg1:string):Promise<void>;

export function ExportData(arg1:Array<main.PageInfo>,arg2:Array<string>):Promise<void>;

export function GetConfig():Promise<main.AppConfig>;

export function GetParseResult(arg1:string):Promise<Array<main.PageInfo>>;

export function GetRecentFiles():Promise<Array<main.RecentFile>>;

export function OpenFiles():Promise<Array<main.RecentFile>>;

export function ParseFile(arg1:string):Promise<Array<main.PageInfo>>;

export function RemoveRecentFile(arg1:string):Promise<Array<main.RecentFile>>;

export function SaveParseResult(arg1:string,arg2:Array<main.PageInfo>):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectExportDir():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<Array<main.RecentFile>>;

export function UpdateConfig(arg1:main.AppConfig):Promise<void>;
